baseURL = "/"
languageCode = "en-us"
title = "æˆ‘åœ¨è¿™é‡Œ"
theme = "hugo-theme-watermelon"
paginate = 6
copyright = "Â© 2022 <a href=\"/\">Sukoshi</a>."
hasCJKLanguage = true
googleAnalytics = "G-GS74WZSLFF"

enableEmoji = true
    
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "base16-snazzy"

# URLæ ¼å¼
[permalinks]
  posts = "/:section/:year:month:day:15:04/"
  docs = "/:section/:year:month:day:15:04/"

# ä½œè€…ä¿¡æ¯
[author]
  name = "Sukoshi"
  email = "guanquanhong@163.com"
  description = "ä¸è§‰å¾—é¹¿è§’å³å¯çˆ±åˆæœ‰æ”»å‡»æ€§å—ï¼ˆ"
  avatar = "https://s.gravatar.com/avatar/7b5a0b07a98895278cfa862b1f32ae8f?s=200&r=g&d=retro"

# èœå•/å¯¼èˆªæ 
[menu]
  # é¡¶éƒ¨å¯¼èˆªæ 
  [[menu.main]]
    identifier = "/"
    name = "ğŸ  HOME"
    title = "HOME"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "/posts"
    name = "ğŸ—‚ï¸ POSTS"
    title = "POSTS"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "/link"
    name = "ğŸ”— LINK"
    title = "LINK"
    url = "/link"
    weight = 4
  [[menu.main]]
    identifier = "/about"
    name = "ğŸ‘´ğŸ» ABOUT"
    title = "ABOUT"
    url = "/about"
    weight = 5
  
  # åº•éƒ¨ç¤¾äº¤å›¾æ ‡
  [[menu.social]]
    identifier = "github"
    name = "github"
    url = "https://github.com/miiiku"
    weight = 1
  [[menu.social]]
    identifier = "twitter"
    name = "twitter"
    url = "https://twitter.com/guanquanhong"
    weight = 2
  [[menu.social]]
    identifier = "instagram"
    name = "instagram"
    url = "https://www.instagram.com/sukoshi_dayo/"
    weight = 3
  [[menu.social]]
    identifier = "weibo"
    name = "weibo"
    url = "https://weibo.com/u/5561168966"
    weight = 4
  [[menu.social]]
    identifier = "zhihu"
    name = "zhihu"
    url = "https://www.zhihu.com/people/miku-84"
    weight = 5

# ä¸»é¢˜ç›¸å…³é…ç½®é¡¹
[params]
  keywords = ["antler", "ä¸ªäººåšå®¢", "ä¸è§é¹¿", "é¹¿è§’"]
  description = "å–œæ¬¢ä¸‹é›¨é—»åˆ°çš„æ³¥åœŸå‘³ï¼Œå–œæ¬¢ä¸‹é›¨å¸¦æ¥çš„ä¸ä¸å‡‰æ„ï¼Œå–œæ¬¢çªåœ¨è¢«çªå¬ç€çª—å¤–å•ªå—’å•ªå—’çš„å£°éŸ³ï¼Œå–œæ¬¢è¢«é›¨å†²åˆ·ä»¥åçš„è¿™ä¸ªä¸–ç•Œ"
  mainSections = ["posts"]

  # å›½å†…å¤‡æ¡ˆå·
  beian = "èœ€ICPå¤‡15014309å·"

  [params.analytics]
    baidu = "77cce6624f1114785af5e77d00cbf93c"

  [params.aplayer]
    theme = "#b7daff"
    autoplay = false
    loop = "none"
    mutex = true

  [params.dplayer]
    theme = "#b7daff"
    autoplay = false
    loop = false
    mutex = true
